/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.letscode;

import com.letscode.dominio.Pessoa;

public class App {

    public static void main(String[] args) throws Exception {
        Pessoa p1 = new Pessoa();
        p1.setIdade(10);
        p1.setNome("Brubru");

        Pessoa p2 = new Pessoa();
        p2.setIdade(23);
        p2.setNome("Gare");

        Pessoa p3 = new Pessoa();
        p3.setIdade(12);
        p3.setNome("Bia");

        Pessoa p4 = new Pessoa();
        p4.setIdade(54);
        p4.setNome("Jorge");

        ListaDePessoas listaPessoas = new ListaDePessoas();

        listaPessoas.adicionar(p1);
        listaPessoas.adicionar(p2);
        listaPessoas.adicionar(p3);
        listaPessoas.adicionar(p4);

        listaPessoas.listarTodos();

        System.out.println("--");
        listaPessoas.remover(0);
        listaPessoas.listarTodos();
        System.out.println("--");
        listaPessoas.remover(1);
        listaPessoas.listarTodos();
        System.out.println("+++");
        listaPessoas.adicionar(p1);
        listaPessoas.adicionar(p2);
        listaPessoas.adicionar(p3);
        listaPessoas.adicionar(p3);
        listaPessoas.adicionar(p3);
        listaPessoas.adicionar(0,p4);

    }
}
